name: Python application

on:
  push:
    # branches: [ "master" ]
  pull_request:
    # branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install test prereqs
        run: |

          cd /; sudo pip install pytest pytest-cov; cd -      
          
    - name: Set up mysql/mariadb
      run: |

        sudo apt-get update
        sudo apt-get install -y mariadb-server
        sudo service mariadb start

        # a simple check that db server is up and running
        # sudo mysql -u root -e "SHOW DATABASES

    - name: initialize db
      run: |

        sudo bin/weedb/tests/setup_mysql.sh
        echo "finished"

        # check that db is setup
        #sudo mysql --force -u root -e "SHOW GRANTS FOR 'weewx'" || true
        #sudo mysql --force -u root -e "select grantee, group_concat(privilege_type) from information_schema.user_privileges group by grantee" || true

    - name: install WeeWX prereq
      run: |        

        sudo apt-get install -y python3-configobj
        sudo apt-get install -y python3-pil
        sudo apt-get install -y python3-serial
        sudo apt-get install -y python3-usb
        sudo apt-get install -y python3-cheetah
        sudo apt-get install -y python3-ephem
        sudo apt-get install -y python3-mysqldb       

    - name: run tests
      run: |        

        # This is a good test to check that the databases are setup
        #PYTHONPATH=bin python3 bin/weedb/tests/test_weedb.py

        # This is a good test that the id has reasonable privileges (not root)
        #PYTHONPATH=bin python3 bin/weedb/tests/test_errors.py

        # This is a nice dimple test
        #PYTHONPATH=bin python3 bin/weewx/tests/test_units.py 

        PYTHONPATH=bin pytest -v bin
