name: Run Tests
# This can be run/tested locally using, https://github.com/nektos/act
# Example invocation:
#     sudo /home/richbell/bin/act push -P ubuntu-latest=catthehacker/ubuntu:runner-latest 
#
# Note: The image catthehacker/ubuntu:runner-latest uses the id 'runner'
#       and the image catthehacker/ubuntu:act-latest uses the id 'root'.
#       Some tests fail when run using 'root'.
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Initialize environment
      run: |
      
        sudo apt-get update

    - name: Install act prereqs
      if: ${{ env.ACT }}
      run: |
        
        sudo apt-get install -yqq python3-pip

    - name: Install test environment prereqs
      run: |

        cd /; sudo pip install pytest pytest-cov; cd -      

    - name: Set up mysql/mariadb
      run: |

        sudo apt-get install -yqq mariadb-server
        sudo service mariadb start

        # a simple check that db server is up and running
        # sudo mysql -u root -e "SHOW DATABASES

    - name: Initialize mysql/mariadb db
      run: |

        sudo bin/weedb/tests/setup_mysql.sh
        echo "finished"

        # check that db is setup
        #sudo mysql --force -u root -e "SHOW GRANTS FOR 'weewx'" || true
        #sudo mysql --force -u root -e "select grantee, group_concat(privilege_type) from information_schema.user_privileges group by grantee" || true

    - name: Install WeeWX prereqs
      run: |        

        sudo apt-get install -yqq python3-configobj
        sudo apt-get install -yqq python3-pil
        sudo apt-get install -yqq python3-serial
        sudo apt-get install -yqq python3-usb
        sudo apt-get install -yqq python3-cheetah
        sudo apt-get install -yqq python3-ephem
        sudo apt-get install -yqq python3-mysqldb       

    - name: Run tests
      run: |        

        # This is a good test to check that the databases are setup
        #PYTHONPATH=bin python3 bin/weedb/tests/test_weedb.py

        # This is a good test that the id has reasonable privileges (not root)
        #PYTHONPATH=bin python3 bin/weedb/tests/test_errors.py

        # This is a nice simple test
        #PYTHONPATH=bin python3 bin/weewx/tests/test_units.py

        # Example of calculating coverage.
        # some of these options generate reports that are currently not used.
        PYTHONPATH=bin pytest -v --junitxml=junit.xml --cov-branch --cov-report term-missing --cov-report xml:coverage.xml --cov-report html:coverage --cov bin bin 

        # Example just running tests
        #PYTHONPATH=bin pytest -v bin

    - name: Upload coverage to Codecov
      if: ${{ !env.ACT }}
      uses: codecov/codecov-action@v3
      with:
        #dry_run: true
        #verbose: true
        fail_ci_if_error: true
        files: ./coverage.xml
        